/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package las.views;

import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import las.models.Permit;

/**
 *
 * @author Uer
 */
public class PermitReminder extends javax.swing.JPanel {
    
    private  ArrayList<Permit> permitList;
    private   FrontPage frontpage;
     GridLayout layout;
    /**
     * Creates new form PermitReminder
     * @param permitList
     * @param frontpage
     */
    public PermitReminder(ArrayList<Permit> permitList,FrontPage frontpage) {
        initComponents();
        this.frontpage=frontpage;
        layout = new GridLayout(0,3,25,5);
        this.setLayout(layout);
        this.add(new JLabel("Permit Number"));
        this.add(new JLabel("Issued Date"));
        this.add(new JLabel());
        this.permitList=permitList;
        displayPermits();
        
              
    }
    
    
    private void displayPermits(){
        for (final Permit permit : this.permitList){
          this.add(new JLabel(permit.getPermitNumber()));
          this.add(new JLabel(permit.getPermitIssueDate()));
          JButton addgrantButton = new JButton("Add Grant");
          this.add(addgrantButton);
          addgrantButton.addActionListener(new ActionListener(){

              @Override
              public void actionPerformed(ActionEvent e) {
                   frontpage.addGrantForReminder(permit);
                   Window w = SwingUtilities.getWindowAncestor(PermitReminder.this);
                   w.dispose();
                      
                
                 
              }
          
              
          });
         
          
          }
        this.revalidate();
        this.repaint();
               

    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
